name = "QuillenSuslin"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["QuillenSuslin"]

[leanOptions]
pp.unicode.fun = true                  # pretty-prints `fun a â†¦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "QuillenSuslin"
